add_newline = false # Disable the newline at the start of the prompt
scan_timeout = 10 # Waiting 10 milliseconds for starship to check files under the current directory.

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
success_symbol = "[ğŸ’—âœ](#00FF00 bold)"
error_symbol = "[ğŸ’”âœ—](bold red)"

[directory]
style = "#ba55d3"
truncation_length = 0
truncate_to_repo = false

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[env_var]
disabled = false

[git_branch]
style = "#dda0dd"
symbol = "â™¥:ï˜ "
truncation_length = 20
truncation_symbol = ""

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³ "
ahead = "ğŸ ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·<200d>"
modified = "ğŸ“"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[hostname]
ssh_only = false
prefix = "âŸª"
suffix = "âŸ«"
trim_at = ".companyname.com"
disabled = true

[jobs]
symbol = "+ "
threshold = 4

[memory_usage]
threshold = -1
symbol = " "
style = "bold dimmed green"

[nodejs]
style = "#ffc0cb"

[ruby]
symbol = "îˆ¾ "
style = "#ffc0cb"

[package]
style = "#ffc0cb"
symbol = "ï£– "
