# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®å…ˆé ­ã«æ”¹è¡Œã‚’è¡¨ç¤ºã—ãªã„
add_newline = false

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªé…ä¸‹ã®ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ç¢ºèªã™ã‚‹ã¾ã§ 10ms å¾…ã¤
scan_timeout = 10

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
success_symbol = "[ğŸš€{ã£*Â´âˆ€`*}ã£ âŸ«âŸ«âŸ«](#00FF00 bold)"
error_symbol = "[ğŸ’£âœ—{ï½¡Â´ï½¥Ï‰ï½¥`} âŸ«âŸ«âŸ«](bold red)"

[directory]
style = "#FF00FF bold"
truncation_length = 0
truncate_to_repo = false
read_only = "ğŸ”’"

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[env_var]
disabled = false

[git_branch]
style = "#7CFC00 bold"
symbol = "ğŸŒ±:ï£– "
truncation_length = 50
truncation_symbol = ""

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³ "
ahead = "ğŸ ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·<200d>"
modified = "ğŸ“"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[hostname]
ssh_only = false
prefix = "âŸª"
suffix = "âŸ«"
trim_at = ".companyname.com"
disabled = true

[jobs]
symbol = "+ "
threshold = 4

[memory_usage]
threshold = -1
symbol = " "
style = "bold dimmed green"

[nodejs]
style = "#FF0000"
symbol = "â¬¢ "

[ruby]
symbol = "îˆ¾ "
style = "#ffc0cb"

[package]
style = "#ffc0cb"
symbol = "ï£– "

[aws]
format = 'on [$symbol$profile(\($region\))]($style) '
style = "#FFFF00 bold"
symbol = "â˜ï¸âš¡ï¸ AWS>> "
[aws.region_aliases]
ap-northeast-1 = "ap-northeast-1"
us-east-1 = "us-east-1"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = "#00FFFF bold"
symbol = "â˜ï¸âš¡ï¸ GCP>> "
[gcloud.region_aliases]
us-central1 = "gcp-uc1"
asia-northeast1 = "gcp-an1"

[docker_context]
format = "via [$symbol](blue bold)"
symbol = "ğŸ³ "
